 let sugestao = [
    'Coronavírus',
    'Auxílio emergencial',
    'Eleições 2020',
    'Eleições EUA',
    'BBB 2020',
    'Copa do Brasil',
    'Google Classroom',
    'Flamengo x São Paulo',
    'Classificação Brasileirão série A',
    'NBA',
    'O que é lockdown?',
    'O que é quarentena?',
    'O que é pandemia?',
    'O que é cadastro único?',
    'O que é coronavírus?',
    'O que é fascismo?',
    'O que é PIX?',
    'O que é yuzu?',
    'O que é sororidade?',
    'O que é Conar?',
    'Como fazer máscara de tecido?',
    'Como fazer álcool em gel?',
    'Como fazer o cadastro único?.',
    'Como fazer avatar no Facebook?',
    'Como fazer o cadastro do auxílio emergencial?',
    'Como fazer que as pessoas gostem de mim?',
    'Como fazer dueto no TikTok?',
    'Como fazer tie dye?',
    'Como fazer live no Instagram?',
    'Como fazer transferência pelo PIX?',
]


